### ISSUE TITLE
How to Align Content center? without class Container

### ISSUE THREAD

**Issue by DjSunrise** [ComputerWolf/996-Grid#4]
Hello!
I have 4 blocks in a row on ne Desktop version.
example

<div class="container clearfix">
    <div class="service-item grid_3"></div> 
    <div class="service-item grid_3"></div> 
    <div class="service-item grid_3"></div> 
    <div class="service-item grid_3"></div> 
</div>

LOOKS WELL! BUT When I see it on mobile it shows 1 block in a row.
I want to view 2 blocks in a row on mobile. 
I can fix this by REMOVING class containet. But now, on the desktop version that 4 blocks shows wrong

**Comment by emilorol** [comment]
My advice is to use a media query to re-size the DIV to 50% and to keep the left float.

Some HTML similar to yours:

``` html
<div class="container">
<div class="grid_3 xs_grid_2">item 1</div>
<div class="grid_3 xs_grid_2">item 2</div>
<div class="grid_3 xs_grid_2">item 3</div>
<div class="grid_3 xs_grid_2">item 4</div>
</div>
```

Then the CSS like:

``` css
/* =============================================================================
   Less than 480px
   ========================================================================== */
@media only screen and (max-width: 479px) {

    /* Container */

    .container { width:300px;}

    /* Global */

    .container .xs_grid_2   {
        width:140px;
        float:left;
    }
}

```
